export const LOGIN_EMAIL_CHANGED = 'LOGIN_EMAIL_CHANGED';
export const LOGIN_PASSWORD_CHANGED = 'LOGIN_PASSWORD_CHANGED';
export const LOGIN_FETCH_PROCESS = 'LOGIN_FETCH_PROCESS';
export const LOGIN_FETCH_SUCCESS = 'LOGIN_FETCH_SUCCESS';
export const LOGIN_FETCH_FAILED = 'LOGIN_FETCH_FAILED';
export const CLEAR_LOGIN_ERROR = 'CLEAR_LOGIN_ERROR';

export const LOGOUT_FETCH_PROCESS = 'LOGOUT_FETCH_PROCESS';
export const LOGOUT_FETCH_SUCCESS = 'LOGOUT_FETCH_SUCCESS';
export const LOGOUT_FETCH_FAILED = 'LOGOUT_FETCH_FAILED';

export const PROFILE_ANNOUNCEMENTS_FETCH_PROCESS = 'PROFILE_ANNOUNCEMENTS_FETCH_PROCESS';
export const PROFILE_ANNOUNCEMENTS_FETCH_SUCCESS = 'PROFILE_ANNOUNCEMENTS_FETCH_SUCCESS';
export const PROFILE_ANNOUNCEMENTS_FETCH_FAILED = 'PROFILE_ANNOUNCEMENTS_FETCH_FAILED';